package com.yavuzmobile.borsaanalizim.model

enum class SortByBalanceSheetRatios {
    STOCK_CODE,
    MARKET_BOOK_AND_BOOK_VALUE,
    PRICE_AND_EARNING,
    COMPANY_VALUE_AND_EBITDA,
    MARKET_VALUE_AND_NET_OPERATING_PROFIT,
    COMPANY_VALUE_AND_NET_SALES,
    NET_OPERATING_PROFIT_AND_MARKET_VALUE
}